# Generated by Django 6.0.3 on 2026-03-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dermatologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100)),
                ('model_response_correct', models.BooleanField(default=False)),
                ('textual_feedback', models.TextField(blank=True, null=True)),
                ('visual_feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
