# Generated by Django 5.2.12 on 2026-05-01 03:32

import dermatology_annotations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dermatologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('occupation', models.CharField(blank=True, default='', max_length=200)),
                ('institution', models.CharField(blank=True, default='', max_length=200)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('current_case_index', models.PositiveIntegerField(default=0)),
                ('current_model_index', models.PositiveIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dermatology_annotations.dermatologist')),
            ],
            options={
                'ordering': ['evaluator', 'order'],
                'unique_together': {('evaluator', 'case_id')},
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('raw_response', models.TextField(blank=True, default='')),
                ('diagnosis_1', models.JSONField(blank=True, default=dict)),
                ('reasoning_1', models.JSONField(blank=True, default=list)),
                ('diagnosis_2', models.JSONField(blank=True, default=dict)),
                ('reasoning_2', models.JSONField(blank=True, default=list)),
                ('diagnosis_3', models.JSONField(blank=True, default=dict)),
                ('reasoning_3', models.JSONField(blank=True, default=list)),
                ('other_feedback', models.JSONField(blank=True, default=dermatology_annotations.models._empty_text_crops)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_entered_at', models.DateTimeField(blank=True, null=True)),
                ('first_completed_at', models.DateTimeField(blank=True, null=True)),
                ('dermatologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='dermatology_annotations.dermatologist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dermatologist', 'case_id', 'model'), name='unique_dermatologist_case_model')],
            },
        ),
        migrations.CreateModel(
            name='TabAuthSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=dermatology_annotations.models._default_tab_session_expiry)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('dermatologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_sessions', to='dermatology_annotations.dermatologist')),
            ],
            options={
                'indexes': [models.Index(fields=['dermatologist', 'expires_at'], name='dermatology_dermato_bd3a3d_idx')],
            },
        ),
    ]
