# Generated by Django 5.2.12 on 2026-04-15 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dermatologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(max_length=100, unique=True)),
                ('current_case_index', models.PositiveIntegerField(default=0)),
                ('current_model_index', models.PositiveIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('interface_type', models.CharField(default='conditional', max_length=20)),
                ('raw_response', models.TextField(blank=True, default='')),
                ('diagnosis_feedback', models.JSONField(blank=True, default=list)),
                ('description_feedback', models.JSONField(blank=True, default=list)),
                ('other_feedback', models.TextField(blank=True, default='')),
                ('other_feedback_crops', models.JSONField(blank=True, default=list)),
                ('user_diagnosis_1', models.TextField(blank=True, default='')),
                ('user_diagnosis_1_crops', models.JSONField(blank=True, default=list)),
                ('user_diagnosis_2', models.TextField(blank=True, default='')),
                ('user_diagnosis_2_crops', models.JSONField(blank=True, default=list)),
                ('user_diagnosis_3', models.TextField(blank=True, default='')),
                ('user_diagnosis_3_crops', models.JSONField(blank=True, default=list)),
                ('user_reasons', models.TextField(blank=True, default='')),
                ('user_reasons_crops', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dermatologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='dermatology_annotations.dermatologist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dermatologist', 'case_id', 'model'), name='unique_dermatologist_case_model')],
            },
        ),
    ]
