# Generated by Django 6.0.3 on 2026-03-24 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermatology_annotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dermatologist',
            name='model_response_correct',
        ),
        migrations.RemoveField(
            model_name='dermatologist',
            name='textual_feedback',
        ),
        migrations.RemoveField(
            model_name='dermatologist',
            name='visual_feedback',
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='current_case_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dermatologist',
            name='login_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100)),
                ('is_done', models.BooleanField(default=False)),
                ('model_response_correct', models.BooleanField(default=False)),
                ('textual_feedback', models.TextField(blank=True, null=True)),
                ('visual_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dermatologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='dermatology_annotations.dermatologist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dermatologist', 'case_id'), name='unique_dermatologist_case')],
            },
        ),
    ]
