# Generated by Django 6.0.3 on 2026-03-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermatology_annotations', '0002_remove_dermatologist_model_response_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='is_done',
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
