# Generated by Django 5.2.12 on 2026-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermatology_annotations', '0002_merge_name_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dermatologist',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='annotation',
            name='diagnosis_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
