# Generated by Django 6.0.4 on 2026-04-17 23:03

import dermatology_annotations.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermatology_annotations', '0003_reconcile_annotation_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabAuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=dermatology_annotations.models._default_tab_session_expiry)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('dermatologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_sessions', to='dermatology_annotations.dermatologist')),
            ],
            options={
                'indexes': [models.Index(fields=['dermatologist', 'expires_at'], name='dermatology_dermato_bd3a3d_idx')],
            },
        ),
    ]
