# Generated by Django 6.0.3 on 2026-03-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dermatology_annotations", "0003_remove_annotation_is_done_dermatologist_is_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="difficulty",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annotation",
            name="review_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
