# Generated by Django 5.2.12 on 2026-05-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermatology_annotations', '0004_alter_annotation_id_alter_assignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dermatologist',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
