# Generated by Django 5.2.12 on 2026-04-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermatology_annotations', '0005_alter_annotation_id_alter_dermatologist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dermatologist',
            name='current_model_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
