# Generated by Django 5.2.12 on 2026-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermatology_annotations', '0005_dermatologist_years_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='benign',
            field=models.BooleanField(default=False),
        ),
    ]
