# Generated by Django 5.2.12 on 2026-05-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermatology_annotations', '0006_annotation_benign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='benign',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='first_completed_at',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='first_entered_at',
        ),
        migrations.AddField(
            model_name='annotation',
            name='page_visits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
