# Generated by Django 5.2.15 on 2026-06-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermatology_annotations', '0010_alter_pcpannotation_id_alter_pcpassignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='marked_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pcpannotation',
            name='marked_complete',
            field=models.BooleanField(default=False),
        ),
    ]
