# Generated by Django 5.2.15 on 2026-06-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dermatology_annotations', '0011_annotation_marked_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dermatologist',
            name='assignment_slot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcpuser',
            name='assignment_slot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
