azure:
  sas_url: "https://YOUR_ACCOUNT_NAME.blob.core.windows.net/model-annotations"
  sas_token: "YOUR_SAS_TOKEN"

upload:
  source_dir: "/scratch/jq2uw/derm_vlms/results"
  container_name: "model-annotations"
  blob_prefix: "datasets/revlm_dc"
  overwrite: false

download:
  container_name: "model-annotations"
  blob_prefix: "datasets/revlm_dc"
  target_dir: "/scratch/jq2uw/derm_vlms/results"
  overwrite: false
