azure:
  sas_url: ""
  sas_token: ""

upload:
  source_dir: "/Users/mgutierrezc/Documents/PhD/Projects/model_editing/repos/derm_vlms/test_folder"
  container_name: "model-annotations"
  blob_prefix: "test_folder"
  overwrite: false

download:
  container_name: "model-annotations"
  blob_prefix: "test_folder"
  target_dir: "/Users/mgutierrezc/Documents/PhD/Projects/model_editing/repos/derm_vlms/test_folder"
  overwrite: false
